<?php


namespace Motionlab\Sauce\Blocks\BannerBlock;

use Motionlab\Sauce\Blocks\Block;

class BannerBlock extends Block
{

    public static $blockAcf = array(
        'key' => 'group_5dd68620097cc',
        'title' => 'Block - Banner',
        'fields' => array(
            array(
                'key' => 'field_5dd6862829f81',
                'label' => 'Full Width',
                'name' => 'banner_full_width',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5de8f02ef89ba',
                'label' => 'Height',
                'name' => 'banner_height',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'min-height-v100' => 'Full Screen Height',
                    'min-height-v75' => '75% Screen Height',
                    'min-height-v50' => '50% Screen Height',
                    'min-height-v25' => '25% Screen Height',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_8c346af6b3ae5',
                'label' => 'Banners',
                'name' => 'banner_banners',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_4006e1e26a5cc',
                        'label' => 'Background Colour',
                        'name' => 'banner_background_colour',
                        'type' => 'clone',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'clone' => array(
                            0 => 'group_5dfb879fe9a51',
                        ),
                        'display' => 'seamless',
                        'layout' => 'block',
                        'prefix_label' => 0,
                        'prefix_name' => 0,
                    ),
                    array(
                        'key' => 'field_5b4e1a6422f52',
                        'label' => 'Layout Style',
                        'name' => 'banner_layout_style',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'standard' => 'Standard Content',
                            'feature-image' => 'Feature Image',
                        ),
                        'default_value' => array(
                            0 => 'standard',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5de8efc7f89b9',
                        'label' => 'Content Position',
                        'name' => 'banner_content_alignment',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'justify-start' => 'Left',
                            'justify-center' => 'Center',
                            'justify-end' => 'Right',
                        ),
                        'default_value' => array(
                            0 => 'justify-left',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_087e7a119064b',
                        'label' => 'Feature Image',
                        'name' => 'banner_feature_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5b4e1a6422f52',
                                    'operator' => '==',
                                    'value' => 'feature-image',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_5dd6878229f82',
                        'label' => 'Content',
                        'name' => 'banner_content',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_d989fcad3032a',
                        'label' => 'Button Alignment',
                        'name' => 'button_alignment',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'left' => 'Left',
                            'center' => 'Center',
                            'right' => 'Right',
                        ),
                        'default_value' => array(),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5defb54d4f5de',
                        'label' => 'Buttons',
                        'name' => 'banner_buttons',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5defb5604f5df',
                                'label' => 'Button',
                                'name' => 'button',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                            ),
                            array(
                                'key' => 'field_5df0cbca1ad90',
                                'label' => 'Icon',
                                'name' => 'icon',
                                'type' => 'font-awesome',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'icon_sets' => array(
                                    0 => 'far',
                                ),
                                'custom_icon_set' => '',
                                'default_label' => '',
                                'default_value' => '',
                                'save_format' => 'element',
                                'allow_null' => 0,
                                'show_preview' => 1,
                                'enqueue_fa' => 0,
                                'fa_live_preview' => '',
                                'choices' => array(
                                ),
                            ),
                            array(
                                'key' => 'field_f078f1bc2dc99',
                                'label' => 'Button Type',
                                'name' => 'button_type',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'default' => 'Default',
                                    'keyline_black' => 'Keyline (Black)',
                                    'keyline_white' => 'Keyline (White)',
                                    'keyline_blue' => 'Keyline (Blue)',
                                ),
                                'default_value' => array(),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'value',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5dd687b429f83',
                        'label' => 'Background Image',
                        'name' => 'banner_background_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_5dd688c429f84',
                        'label' => 'Overlay Colour',
                        'name' => 'banner_overlay_colour',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                    ),
                    array(
                        'key' => 'field_5de8f298bb3c1',
                        'label' => 'Overlay Opacity',
                        'name' => 'banner_overlay_opacity',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'opacity-1' => '1',
                            'opacity-2' => '2',
                            'opacity-3' => '3',
                            'opacity-4' => '4',
                            'opacity-5' => '5',
                            'opacity-6' => '6',
                        ),
                        'default_value' => array(
                        ),
                        'allow_null' => 1,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    )
                )
            )
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => false,
        'description' => '',
    );

    public function init() {
        include(__DIR__ . '/block.php');
    }
}
